multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: right_arm
    base_link: upper
    tip_link: handmount_RIGHT
default_collision_operations:
  - object1: base_link
    object2: upper
    operation: disable  # Adjacent in collision
  - object1: upper
    object2: shoulderupper_RIGHT
    operation: disable  # Adjacent in collision
  - object1: shoulderupper_RIGHT
    object2: shoulderpitch_RIGHT
    operation: disable  # Adjacent in collision
  - object1: shoulderpitch_RIGHT
    object2: bicep_RIGHT
    operation: disable  # Adjacent in collision
  - object1: bicep_RIGHT
    object2: elbowclevis_RIGHT
    operation: disable  # Adjacent in collision
  - object1: elbowclevis_RIGHT
    object2: wrist_RIGHT
    operation: disable  # Adjacent in collision
  - object1: wrist_RIGHT
    object2: w_differential_RIGHT
    operation: disable  # Adjacent in collision
  - object1: w_differential_RIGHT
    object2: handmount_RIGHT
    operation: disable  # Adjacent in collision
  - object1: bicep_RIGHT
    object2: handmount_RIGHT
    operation: disable  # Never in collision
  - object1: bicep_RIGHT
    object2: shoulderupper_RIGHT
    operation: disable  # Never in collision
  - object1: bicep_RIGHT
    object2: w_differential_RIGHT
    operation: disable  # Never in collision
  - object1: bicep_RIGHT
    object2: wrist_RIGHT
    operation: disable  # Never in collision
  - object1: elbowclevis_RIGHT
    object2: handmount_RIGHT
    operation: disable  # Never in collision
  - object1: elbowclevis_RIGHT
    object2: shoulderpitch_RIGHT
    operation: disable  # Never in collision
  - object1: elbowclevis_RIGHT
    object2: shoulderupper_RIGHT
    operation: disable  # Never in collision
  - object1: elbowclevis_RIGHT
    object2: w_differential_RIGHT
    operation: disable  # Never in collision
  - object1: handmount_RIGHT
    object2: shoulderpitch_RIGHT
    operation: disable  # Never in collision
  - object1: handmount_RIGHT
    object2: shoulderupper_RIGHT
    operation: disable  # Never in collision
  - object1: handmount_RIGHT
    object2: wrist_RIGHT
    operation: disable  # Never in collision
  - object1: shoulderpitch_RIGHT
    object2: upper
    operation: disable  # Never in collision
  - object1: shoulderpitch_RIGHT
    object2: w_differential_RIGHT
    operation: disable  # Never in collision
  - object1: shoulderpitch_RIGHT
    object2: wrist_RIGHT
    operation: disable  # Never in collision
  - object1: shoulderupper_RIGHT
    object2: w_differential_RIGHT
    operation: disable  # Never in collision
  - object1: shoulderupper_RIGHT
    object2: wrist_RIGHT
    operation: disable  # Never in collision